export const ECONOMY_CONFIG = {
  SIGNUP_BONUS_TOKENS: 1000,
  MIN_PREDICTION_AMOUNT: 10,
  MAX_PREDICTION_PER_MARKET: 500,
  DEFAULT_YES_SEED: 500,
  DEFAULT_NO_SEED: 500,
  FEE_BPS: 0,
  DAILY_CLAIM_TOKENS: 0,
  MARKET_CREATION_COST: 0,
} as const;

export type EconomyConfig = typeof ECONOMY_CONFIG;
